version: '3.9'

services:
  cardchecker-api:
    container_name: cardchecker-api
    build: ./app
    restart: unless-stopped
    env_file:
      - ./api.env
      - ./db.env
    ports:
      - 3001:3000
    networks:
      - internal
      - service
      - worker-api_service
    volumes:
      - ./certs:/app/certs:ro

  cardchecker-db:
    container_name: cardchecker-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    env_file:
      - ./db.env
    networks:
      - internal
    volumes:
      - ./data:/var/lib/postgresql/data


networks:
  service:
  internal:
  worker-api_service:
    external: true
