name: "Docker Build"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  build-project:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
        version: [ 19 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Create the envs
        run: cp api.env.example api.env; cp db.env.example db.env;

      - name: try to build the project
        run: docker-compose build;
