name: "Code quality"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  quality-prettier:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
        version: [ 19 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install packages
        run: cd app; yarn

      - name: Run prettier
        run: cd app; yarn run linter
